baseURL = "http://example.org/"
languageCode = "en-us"
title = "Systematik"
theme = "systematik"
sectionPagesMenu = "mainMenu"

[params]
	themeColor = "blue"
	brand = "Systematik"
	# Optional logo as brand stored in img/
	logo = "logo.svg"

# Site - Header
[params.header]
	columnStart 	= "s-c-1 m-c-2 l-c-1"
	columnSpan 		= "s-cs-3 l-cs-2"

	rowStart		= "s-r-2 m-r-1"
	rowSpan			= "s-rs-1"

	menu = "1"
		menuTitle = "Documentation"
		subMenuTheme = "black"

		menuColumnStart 	= "s-c-1"
		menuColumnSpan 		= "s-cs-3 m-cs-1 l-cs-2"

		menuRowStart 		= "s-r-1 l-r-2"
		menuRowSpan 		= "s-rs-1 m-rs-2 l-rs-1"

[params.sections]
	row1 = "section1"
	row2 = "section2"
	row3 = "section3"
	row4 = "section4"
	row5 = "section5"
	row6 = "section6"

# Main | Section - 1
[params.section1]
	enable = true
	slug = "get-started"

	columnStart 	= "s-c-1 m-c-2 l-c-1"
	columnSpan 		= "s-cs-3 l-cs-2"

	rowStart		= "s-r-2 m-r-1"
	rowSpan			= "s-rs-1"

	subSection = "1"

	subMenu = "1"
		subMenuTitle = "Test"
		subMenuTheme = "light"

		subMenuColumnStart 	= "s-c-1"
		subMenuColumnSpan 	= "s-cs-3 m-cs-1 l-cs-2"

		subMenuRowStart		= "s-r-1 l-r-2"
		subMenuRowSpan 		= "s-rs-1 m-rs-2 l-rs-1"


# Sub Menu - 1
[[menu.menu1]]
	name = "Get Started"
	url = "#get-started"
	weight = 1
	pre = "<i class='fas fa-terminal icon-border ani-1'></i>"

[[menu.menu1]]
	name = "Style"
	url = "#style"
	weight = 2

[[menu.menu1]]
	name = "Components"
	url = "#components"
	weight = 3


# Sub Menu - 2
[[menu.submenu2]]
	name = "Link 2"
	url = "#"
	weight = 20

[[menu.submenu3]]
	name = "Link 3"
	url = "#"
	weight = 20
