baseurl = "http://example.com/"
languageCode = "en-us"
title = "Systematik"
theme = "systematik"
sectionPagesMenu = "mainMenu"
#themesdir = "../.."

[params]
	themeColor = "blue"
	brand = "Systematik"
	# Optional logo as brand stored in img/
	logo = "logo.svg"

# Site - Header
[params.header]
	enable = true
	
	subSection = "1"

	menu = "1"
		menuTitle = "Documentation"
		menuTheme = "black"

	# xs / Xtra Small:	Screen under 468px
	# sm / Small:		Screen between 468px & 768px
	# md / Medium:		Screen between 768p & 1200px
	# lg / Large:		Screen over 1200px

		####theme = ""
		style = "xs-col sm-col sm-col-row md-row"

		styleArticle		= ""
		styleContent		= ""
		styleMenu			= "bottom-lg"
		styleSubSection		= ""

		orderArticle		= "odr-xs-1"
		orderContent		= "odr-xs-2 odr-sm-1 odr-md-2"
		orderMenu			= "odr-xs-1 odr-sm-2 odr-md-1 odr-lg-2"
		orderSubSection		= "odr-xs-3"

		columnArticle		= "col-xs-12 col-lg-9"
		columnContent		= "col-xs-12 col-md-8 col-lg-12"
		columnMenu			= "col-xs-12 col-md-4 col-lg-12"
		columnSubSection	= "col-xs-12 col-md-12 col-lg-3"


[params.sections]
	row1 = "section1"
	row2 = "section2"
	row3 = "section3"
	row4 = "section4"
	row5 = "section5"
	row6 = "section6"

# Main | Section - 1
[params.section1]
	enable = true
	slug = "get-started"
	
	#subSection = "2"

	subMenu = "1"
		#subMenuTitle = "Get Started"
		subMenuTheme = "black"

	# xs / Xtra Small:	Screen under 468px
	# sm / Small:		Screen between 468px & 768px
	# md / Medium:		Screen between 768p & 1200px
	# lg / Large:		Screen over 1200px

		####theme = ""
		style = "xs-row"

		styleArticle		= ""
		styleContent		= ""
		styleSubMenu		= ""
		styleSubSection		= ""

		orderArticle		= "odr-xs-1"
		orderContent		= "odr-xs-1 odr-lg-2"
		orderSubMenu		= "odr-xs-1"
		orderSubSection		= "odr-xs-1"

		columnArticle		= "col-xs-12"
		columnContent		= "col-xs-12 col-lg-8"
		columnSubMenu		= "col-xs-12 col-lg-4"
		columnSubSection	= "col-xs-12"


# Menu - 1
[[menu.menu1]]
	name = "Get Started"
	url = "#get-started"
	weight = 1
	pre = "<i class='fas fa-terminal icon-border ani-1'></i>"

[[menu.menu1]]
	name = "Style"
	url = "#style"
	weight = 2

[[menu.menu1]]
	name = "Components"
	url = "#components"
	weight = 3


# Sub Menu - 1
[[menu.submenu1]]
	name = "Link 2"
	url = "#"
	weight = 20
